### ISSUE TITLE
Error object on failure?

### ISSUE THREAD

**Issue by iansinnott** [kryptnostic/kryptnostic-js#154]
Hey team, is there any error object passed to the `catch` call for `registrationClient.register`?

Just wondering if there is any information available on the reason for failure.

**Comment by UnsungHero97** [comment]
hey @iansinnott , it doesn't seem like there is a `catch` in `registrationClient.register`; we should probably fix this. what would you like to see happen?

**Comment by iansinnott** [comment]
Going off the example in the docs right now, it would be nice to see an error object that gave some indication of what went wrong:

```js
var registrationClient = new KJS.RegistrationClient();

registrationClient.register({ 'krypto@kryptnostic.com', 'krypto', 'mansbestfriend1^' })
.then(function() {
    // confirm successful registration.
})
.catch(function(err) { // <-- Added error object as argument
  // registration failed :(
  window.alert('Sorry, registration failed. ' + err.message); 
});
```

Even if the error message was ambiguous for security reasons it would be nice to have something to show the user to give them some indication of what went wrong.

In the event that there are multiple reasons the promise would reject it would also be nice to know what went wrong from a dev perspective. For example, if the request fails because the user has a shoddy internet connection then I would expect a different `err` object than if the username they tried to register is already taken.

**Comment by UnsungHero97** [comment]
@iansinnott at the moment, we don't explicitly provide an error object. however, the `err` object you're referring to will be available to you, so the example code will work. that said, the error message won't be very useful to you since we don't have proper error handling in place.

to do proper error handling will involve a lot of work, including changes to our backend. this work is slated for KJS v2, but the timeline is not yet fleshed out.
